import React from 'react';
import Header from '../components/Header';
import { CheckCircle, UserCheck, MessageSquare, BarChart3, Play, FileText } from 'lucide-react';

const HowItWorks = () => {
  const steps = [
    {
      icon: <UserCheck className="h-8 w-8 text-indigo-600" />,
      title: "Sign Up & Create Profile",
      description: "Create your account and set up your professional profile with your skills and experience level."
    },
    {
      icon: <Play className="h-8 w-8 text-indigo-600" />,
      title: "Start New Interview",
      description: "Choose your job role, enter the job description, and specify your experience level to generate tailored questions."
    },
    {
      icon: <MessageSquare className="h-8 w-8 text-indigo-600" />,
      title: "Answer Questions",
      description: "Practice with AI-generated interview questions. Use voice recording or text input to provide your answers."
    },
    {
      icon: <BarChart3 className="h-8 w-8 text-indigo-600" />,
      title: "Get Instant Feedback",
      description: "Receive detailed feedback on your performance, including ratings and suggestions for improvement."
    },
    {
      icon: <FileText className="h-8 w-8 text-indigo-600" />,
      title: "Review & Improve",
      description: "Access your interview history, compare your answers with ideal responses, and track your progress over time."
    }
  ];

  const features = [
    {
      title: "AI-Powered Questions",
      description: "Get industry-specific questions generated by advanced AI based on your job description and experience level.",
      icon: "🤖"
    },
    {
      title: "Real-time Voice Recording",
      description: "Practice speaking your answers with our voice recording feature that simulates real interview conditions.",
      icon: "🎤"
    },
    {
      title: "Detailed Performance Analytics",
      description: "Receive comprehensive feedback with ratings, improvement areas, and comparison with ideal answers.",
      icon: "📊"
    },
    {
      title: "Industry-Specific Preparation",
      description: "Customize your practice sessions for different industries and job roles to match your career goals.",
      icon: "🎯"
    }
  ];

  return (
    <div className="min-h-screen bg-gray-50">
     
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Header Section */}
        <div className="text-center mb-16">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">How AI Interview Pro Works</h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Master your interview skills with our AI-powered mock interview platform. 
            Get personalized feedback and improve your performance step by step.
          </p>
        </div>

        {/* Steps Section */}
        <div className="mb-20">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">5 Simple Steps to Success</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {steps.map((step, index) => (
              <div key={index} className="relative bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
                <div className="flex items-center mb-4">
                  <div className="p-3 bg-indigo-100 rounded-lg mr-4">
                    {step.icon}
                  </div>
                  <div className="w-8 h-8 bg-indigo-600 text-white rounded-full flex items-center justify-center text-sm font-bold">
                    {index + 1}
                  </div>
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">{step.title}</h3>
                <p className="text-gray-600">{step.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Features Section */}
        <div className="mb-16">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">Key Features</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="bg-white p-6 rounded-xl shadow-lg">
                <div className="text-4xl mb-4">{feature.icon}</div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">{feature.title}</h3>
                <p className="text-gray-600">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Benefits Section */}
        <div className="bg-indigo-50 rounded-2xl p-8 mb-16">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-8">Why Choose AI Interview Pro?</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              "Practice anytime, anywhere",
              "Reduce interview anxiety",
              "Improve communication skills",
              "Get industry-specific feedback",
              "Track your progress over time",
              "Boost your confidence",
              "Prepare for different interview formats",
              "Learn from detailed analytics",
              "Save time and money on interview prep"
            ].map((benefit, index) => (
              <div key={index} className="flex items-center space-x-3">
                <CheckCircle className="h-5 w-5 text-green-600 flex-shrink-0" />
                <span className="text-gray-700">{benefit}</span>
              </div>
            ))}
          </div>
        </div>

        {/* CTA Section */}
        <div className="text-center bg-gradient-to-r from-indigo-600 to-purple-600 rounded-2xl p-8 text-white">
          <h2 className="text-3xl font-bold mb-4">Ready to Ace Your Next Interview?</h2>
          <p className="text-xl mb-6 opacity-90">
            Join thousands of professionals who have improved their interview skills with AI Interview Pro.
          </p>
          <button className="bg-white text-indigo-600 px-8 py-3 rounded-lg font-semibold text-lg hover:bg-gray-100 transition-colors">
            Start Practicing Now
          </button>
        </div>
      </div>
    </div>
  );
};

export default HowItWorks;